// models/HospitalClient.js
const mongoose = require('mongoose');
const ClientSchema = new mongoose.Schema({
  vendorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, // 도매상
  classification: String,
  code: String,
  nameInternal: String,
  nameOriginal: String,
  representative: String,
  dob: Date,
  businessNumber: String,
  phone: String,
  fax: String,
  zip: String,
  address: String,
  salesRep: String,
  deptHead: String,
  priceApply: String,
  stockApply: String,
  invoiceIssue: Boolean,
  businessType: String,
  item: String,
  clientType: String,
  clientGroup: String,
  contractType: String,
  deliveryType: String,
  pharmacist: String,
  licenseNo: String,
  careNo: String,
  narcoticsId: String,
  deviceClient: String,
  contact: String,
  email: String,
  invoiceManager: String,
  managerPhone: String,
  creditLimit: Number,
  maxTurnDays: Number,
  monthlyEstimate: Number,
  startDate: Date,
  note1: String,
  note2: String,
  active: Boolean,
  eInvoice: Boolean,
  invoiceSystem: String,
  externalExclude: Boolean,
  prePayment: Boolean,
  createdAt: { type: Date, default: Date.now },
});
module.exports = mongoose.model('HospitalClient', ClientSchema);
